### ISSUE TITLE
عدم ساپورت تروجان و vless

### ISSUE THREAD

**Issue by mojvat** [seezaara/RocketV2ray#1]
سلام 
لطفا قابلیت ساپورت پروتکل های دیگر هم بهش اضافه کنید اگر قابلیلت سابسکرایب هم اضافه کنی خیلی خوب می شه

**Comment by seezaara** [comment]
فعلا تروجان و vless رو از طریق کانفیگ json میتونی وارد کنی توی اپدیت بعدی اضافه میشه

**Comment by seezaara** [comment]
توی ورژن 1.2.0 اضافه شد
