### ISSUE TITLE
support TUIC wireguard Hysteria Hysteria2

### ISSUE THREAD

**Issue by Morrigan-Ship** [seezaara/RocketV2ray#4]
support TUIC wireguard Hysteria Hysteria2
if you adding wireguard remember it can support warp on warp

**Comment by Morrigan-Ship** [comment]
Please add TUIC wireguard Hysteria Hysteria2
for wireguard use GFW-Knocker xray core
or you can make an option to let user select custom core

**Comment by seezaara** [comment]
you can use source of project for add more option to it. its pretty simple and easy and i have a video to how run the project.

**Comment by Morrigan-Ship** [comment]
رکب خوردیم گرگعلی

**Comment by seezaara** [comment]
گرگعلی اگر ادیتی چیزی زدی تو تلگرام برام بفرست سورس اپدیت کنم
https://t.me/seezaara
> رکب خوردیم گرگعلی
